FROM apache/spark:3.5.0

USER root

# Baixar JARs necessários para S3
RUN cd /opt/spark/jars && \
    wget -q https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-aws/3.3.4/hadoop-aws-3.3.4.jar && \
    wget -q https://repo1.maven.org/maven2/com/amazonaws/aws-java-sdk-bundle/1.12.262/aws-java-sdk-bundle-1.12.262.jar

# Adicionar Python ao PATH
ENV PYTHONPATH="/opt/spark-app:${PYTHONPATH}"

USER 185
